export const skills = [
  { name: "HTML5", index: 0 },
  { name: "CSS3", index: 1 },
  { name: "JavaScript", index: 2 },
  { name: "TypeScript", index: 3 },
  { name: "Go", index: 4 },
  { name: "Python", index: 5 },
  { name: "React", index: 6 },
  { name: "Next.js", index: 7 },
  { name: "MySQL", index: 8 },
  { name: "MongoDB", index: 9 },
  { name: "Firebase", index: 10 },
  { name: "PostgreSQL", index: 11 },
  { name: "SQLite", index: 12 },
  { name: "Supabase", index: 13 },
  { name: "Git", index: 14 },
  { name: "GitHub", index: 15 },
  { name: "Postman", index: 16 },
  { name: "Clerk", index: 17 },
  { name: "shadcnui", index: 18 },
  { name: "npm", index: 19 },
  { name: "Prisma", index: 20 },
  { name: "Zod", index: 21 },
  { name: "Vercel", index: 22 },
  { name: "Framer Motion", index: 24 },
];
